### ISSUE TITLE
Menu della mensa non disponibile

### ISSUE THREAD

**Issue by cbranca** [fcapano/UnisaConnect#10]
Da quando è cambiata la gestione della mensa, il sito che si occupa di estrarre il menu della mensa non riesce più a fare parsing del pdf. Di conseguenza la funzionalità Menu mensa dell'app restituisce sempre il messaggio "il menu non è disponibile oggi... Pranzo a sorpresa :p".
Il problema ovviamente è del sito che fa il parsing, ma volevo segnalarvelo lo stesso.

**Comment by axl8713** [comment]
Sono lo sviluppatore della pagina che mostra il menu della mensa. 
Come puoi intuire, la struttura del pdf è soggetto a frequenti variazioni e non è sempre semplice correggere.
Ad ogni modo, adesso sembra funzionare...
