### ISSUE TITLE
Set up sviluppo

### ISSUE THREAD

**Issue by mattmezza** [fcapano/UnisaConnect#4]
*Salve ragazzi, complimenti per l'app.*

Ho provato a riprodurre l'ambiente di sviluppo per contribuire al progetto però non sono riuscito a mandare in run il progetto. Probabilmente ci sono alcune dipendenze che non riesco a soddisfare. Visto che UnisaConnect è Open Source, che ne dite di includere tali dipendenze in maniera da semplificare la vita a chi vuole dare una mano a rendere l'app sempre più performante? 
Magari un how to (anche nel README) su come impostare il progetto per essere subito operativi riuscirebbe ad aiutare chi vuole dare una mano! ;)

**Comment by fcapano** [comment]
Ciao Matteo,
hai ragione, in effetti è una cosa che volevo fare già da un po' di tempo. In questo periodo (il tempo non è molto purtroppo) cercherò di aggiornare il repository eliminando dipendenze inutili, migrando il progetto ad Android Studio visto che lo sviluppo su Eclipse è stato deprecato, e aggiungendo qualche informazione di setup iniziale. Ti tengo aggiornato tramite questo issue ;)

**Comment by mattmezza** [comment]
Ottimo! :+1: 
Non vedo l'ora!

**Comment by fcapano** [comment]
Ciao Matteo,
e' passato un po di tempo (cough cough) ma finalmente ho fatto la migrazione del progetto da Eclipse a Android Studio.
Cerchero' di caricare le modifiche e le istruzioni di setup in questo fine settimana!

**Comment by mattmezza** [comment]
Perfetto! In realtà, oltre che collaborare allo sviluppo, mi piacerebbe
incontrarti per parlare di un progetto che ho in mente!
Se hai tempo e ti trovi a Fisciano mandami una mail o un messaggio
mattmezza@gmail.com 3409341277

😉

**Comment by fcapano** [comment]
Fixed by de300b812109d54ac089fb8814889846e908cf0a
Eliminate le varie dipendente. Dovrebbe essere sufficiente importare il repository in Android Studio per avere un setup funzionante
