### ISSUE TITLE
pannello privacy impossibile da nascondere

### ISSUE THREAD

**Issue by mattmezza** [fcapano/UnisaConnect#7]
![unisaconn](https://cloud.githubusercontent.com/assets/1915989/11020886/163817f8-862f-11e5-8028-13ca045cb00f.png)
sembra che il pannello della privacy sia impossibile da rimuovere.

In #6 provo a dare una soluzione.

**Comment by fcapano** [comment]
Fixed by de300b812109d54ac089fb8814889846e908cf0a
